version: "3.9"
services:
  checker:
    build:
      dockerfile: Dockerfile
      context: .
    command: python rule-keeper/main.py
    volumes:
      - "..:/usr/src/app:ro"
  tests:
    build:
      dockerfile: Dockerfile
      context: .
    command: python -m unittest
    volumes:
      - ".:/usr/src/app:ro"