title: /dev/solita
description: A place where the developers from Solita share their knowledge.
authors:
  jarno:
    name: Jarno Peltoniemi
    url: mailto:jarno.peltoniemi@solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    url: http://ajk.fi/
  massimo:
    name: Massimo Prencipe
    url: mailto:massimo.prencipe@solita.fi
