title: /dev/solita, Solita developer blog
description: Coder, what is best in life? To crush your bugs, see tests automatically driven before you and hear the lamentation of our competitors.
authors:
  jarno:
    name: Jarno Peltoniemi
    email: jarno.peltoniemi@solita.fi
    url: mailto:jarno.peltoniemi@solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    email: ajk@solita.fi
    url: http://ajk.fi/
  massimo:
    name: Massimo Prencipe
    email: massimo.prencipe@solita.fi
    url: mailto:massimo.prencipe@solita.fi
  lokori:
    name: Antti Virtanen
    email: antti.virtanen@solita.fi
    url: mailto:antti.virtanen@solita.fi

